version: '2'
services:
  web:
    image: local/drupal8
    volumes: 
      - ~/drupal/drupal8:/var/www/html
      - ~/drupal/drupal8/docker/conf/apache2/apache2.conf:/etc/apache2/apache2.conf
      - ~/drupal/drupal8/docker/conf/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    ports:
      - "80:80"
    links:
        - database:database
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
     - PMA_ARBITRARY=1
    restart: always
    ports:
     - 8080:80
    volumes:
     - ~/drupal/drupal8/docker/data/phpmyadmin:/sessions
    links:
        - database:database
  database:
    image: mariadb:10
    environment:
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_DATABASE: drupal
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - 3306:3306
    volumes:
      - ~/drupal/drupal8/docker/data/mysql:/var/lib/mysql:rw
    restart: always
